# Generated by Django 4.0.2 on 2022-05-31 19:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='Tags',
            new_name='tag',
        ),
    ]
