# Generated by Django 4.0.2 on 2022-06-06 14:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0005_vote'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='location',
        ),
        migrations.RemoveField(
            model_name='post',
            name='tag',
        ),
        migrations.DeleteModel(
            name='Location',
        ),
        migrations.DeleteModel(
            name='Tag',
        ),
    ]
